name: trigger-remote-workflow

on:
  push:
    branches:
    - development
    paths:
    - '!.github/**'
  pull_request:
    branches:
    - development
    paths:
    - '!.github/**'
  workflow_dispatch:
    inputs:
      workflow-name:
        description: Name of workflow to run in cicd-infra-pc-team
        required: true
        default: build-petclinic

jobs:
  remote-job:
    runs-on: [ "pc", "kickstart" ]
    steps:
    - name: Setup environment
      run: |
        echo "TEAM_INFRA_REPOSITORY=nicks-world/cicd-infra-pc-team" >> ${GITHUB_ENV}
        echo "WORKFLOW_NAME=${GITHUB_WORKSPACE}/${{ github.event.inputs.workflow-name }}" >> ${GITHUB_ENV}
        CICD_SECRET_YOU_SHOULD_NOT_SEE='some_secret_test_data_that_should_be_hidden'

        echo "::add-mask::${CICD_SECRET_YOU_SHOULD_NOT_SEE}"

        echo "FOO=${CICD_SECRET_YOU_SHOULD_NOT_SEE}" >> ${GITHUB_ENV}
        echo "CICD_SECRET_YOU_SHOULD_NOT_SEE: ${CICD_SECRET_YOU_SHOULD_NOT_SEE}"
        echo "FOO: ${FOO}"
        echo "env.FOO: ${{ env.FOO }}"
    - name: Checkout CICD infra library
      uses: actions/checkout@v2
      with:
        repository: ${{ env.TEAM_INFRA_REPOSITORY }}
        ref: main
        path: ${{ env.TEAM_INFRA_REPOSITORY }}
        token: ${{ env.CICD_SECRET_YOU_SHOULD_NOT_SEE }}
    - name: Trigger remote workflow
      run: |
        ${GITHUB_WORKSPACE}/${TEAM_INFRA_REPOSITORY}/scripts/trigger-remote-workflow/trigger-remote-workflow.sh

