name: trigger-remote-workflow

on:
  push:
    branches:
    - development
    paths:
    - '!.github/**'
  pull_request:
    branches:
    - development
    paths:
    - '!.github/**'
  workflow_dispatch:
    inputs:
      workflow-name:
        description: Name of workflow to run in cicd-infra-pc-team
        required: true
        default: build-petclinic

jobs:
  remote-job:
    runs-on: ubuntu-latest
    env:
      TEAM_INFRA_REPOSITORY: nicks-world/cicd-infra-pc-team
      CICD_INFRA_SVC_ACCT_PAT: ${{ secrets.CICD_TOKEN }}
      WORKFLOW_NAME: ${{ github.event.inputs.workflow-name }}
    steps:
    - name: Checkout CICD infra library
      uses: actions/checkout@v2
      with:
        repository: ${{ env.TEAM_INFRA_REPOSITORY }}
        ref: main
        path: cicd-infra-pc-team
        token: ${{ secrets.CICD_TOKEN }}
    - name: Trigger remote workflow
      run: |
        ${GITHUB_WORKSPACE}/cicd-infra-pc-team/scripts/trigger-remote-workflow/trigger-remote-workflow.sh ${WORKFLOW_NAME} ${CICD_INFRA_SVC_ACCT_PAT}

