name: trigger-remote-workflow

on:
  workflow_dispatch:
    inputs:
      workflow-name:
        description: Name of workflow to run in cicd-infra-pc-team
        required: true
        default: build-petclinic

jobs:
  remote-job:
    runs-on: ubuntu-latest
    env:
      CICD_INFRA_SVC_ACCT_PAT: ${{ secrets.CICD_INFRA_SVC_ACCT_PAT }}
      WORKFLOW_NAME: ${{ github.event.inputs.workflow-name }}
    steps:
    - name: Checkout CICD infra library
      uses: actions/checkout@v2
      with:
        repository: nicks-world/cicd-infra-pc-team
        ref: master
        path: cicd-infra-pc-team
        token: ${{ secrets.CICD_INFRA_SVC_ACCT_PAT }}
    - name: Trigger remote workflow
      run: |
        ${GITHUB_WORKSPACE}/cicd-infra-pc-team/scripts/trigger-remote-workflow/trigger-remote-workflow.sh ${WORKFLOW_NAME} ${CICD_INFRA_SVC_ACCT_PAT}

